site_name: FastLimits
site_description: A rate limiting extension for FastAPI
site_url: https://astronuttt.github.io/fastlimits

theme:
  name: 'material'
  palette:
    scheme: slate
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - content.code.copy

  logo: 'img/icon.webp'
  favicon: 'img/icon.webp'

repo_name: astronuttt/fastlimits
repo_url: https://github.com/astronuttt/fastlimits

nav:
  - FastLimits: 'index.md'
  - User Guide:
    - Why?: 'user-guide/why.md'
    - Installation: 'user-guide/install.md'
    - Getting started: 'user-guide/getting-started.md'
    - Middlewares: 'user-guide/middlewares.md'
    - Keys: 'user-guide/keys.md'
    - Filters: 'user-guide/filters.md'
    - Examples: 'user-guide/examples.md'
  - API Refrence:
    - Limiter: 'api-refrence/limiter.md'
    - Middleware: 'api-refrence/middleware.md'
    - Dependencies: 'api-refrence/dependencies.md'
    - Functions: 'api-refrence/functions.md'
    - Exceptions: 'api-refrence/exceptions.md'
    - Utils: 'api-refrence/utils.md'
    - Types: 'api-refrence/types.md'


plugins:
  search:
    lang: en
  mkdocstrings:
    handlers:
      python:
        options:
          allow_inspection: true
          show_signature_annotations: true
          separate_signature: true
          unwrap_annotated: true
          signature_crossrefs: true
          show_if_no_docstring: true
          members_order: source
          members: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true